version: 0.0
os: linux
files:
  - source: /  # 从源码目录复制文件
    destination: /home/ec2-user/my-go-app  # 目标路径
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
